["â« Code Elevation"]
color = "1d76db"
name = "â« Code Elevation"
description = "Minor merge without breaking changes"

["âš™ï¸ Settings"]
color = "6b759b"
name = "âš™ï¸ Settings"
description = "Basic configuration of the project"

["ğŸ¨ Design"]
color = "281a7f"
name = "ğŸ¨ Design"
description = "Design related"

["ğŸ— Develop"]
color = "0e8a16"
name = "ğŸ— Develop"
description = "Code in development stage"

["ğŸ‘¨ğŸ»â€ğŸ’» Development"]
color = "c1f745"
name = "ğŸ‘¨ğŸ»â€ğŸ’» Development"
description = "Development related"

["ğŸ‘» Metadata"]
color = "a6a7b0"
name = "ğŸ‘» Metadata"
description = "SEO and meta-information related code"

["ğŸ’…ğŸ» CSS"]
color = "4f44e5"
name = "ğŸ’…ğŸ» CSS"
description = "CSS styles related code"

["ğŸ’ªğŸ» Javascript"]
color = "fef2c0"
name = "ğŸ’ªğŸ» Javascript"
description = "Javascript related code"

["ğŸ“œ Shell Script"]
color = "DEE8F2"
name = "ğŸ“œ Shell Script"
description = "Scripts related"

["ğŸ“ Content"]
color = "cba8f7"
name = "ğŸ“ Content"
description = "Content related data"

["ğŸ“¦ Laika v0.0.0"]
color = "f7e1bb"
name = "ğŸ“¦ Laika v0.0.0"
description = "Codename of the release"

["ğŸš€ Deploy"]
color = "0e8a16"
name = "ğŸš€ Deploy"
description = "Code ready to production stage"

["ğŸš¨ Fix"]
color = "b60205"
name = "ğŸš¨ Fix"
description = "General fix on the bundle"

["ğŸ›  Refactor"]
color = "0052cc"
name = "ğŸ›  Refactor"
description = "Changes and optimization of the Code and Content"

["ğŸ¦´ HTML"]
color = "fbca04"
name = "ğŸ¦´ HTML"
description = "Markup HTML related code"

["ğŸ§¨ Bug Fix"]
color = "d93f0b"
name = "ğŸ§¨ Bug Fix"
description = "Specific fix of the bundle"
